# This file was generated by GoReleaser. DO NOT EDIT.
cask "loops@0.4.1" do
  version "0.4.1"

  on_macos do
    on_intel do
      sha256 "c538807b6553f26377c46b044c25776c334453ad0c5d7f1948332349c6ac6278"
      url "https://github.com/Loops-so/cli/releases/download/v#{version}/loops_cli_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "1fd6d670899ec6dc1fcd831a417e8e9e72f6060d2f40a9f082e1c48aac57b3c6"
      url "https://github.com/Loops-so/cli/releases/download/v#{version}/loops_cli_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6f292aaf2210880d157465eb9b2c73957e8cda1124c0d83afb783898689a1d3b"
      url "https://github.com/Loops-so/cli/releases/download/v#{version}/loops_cli_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "7013d189692fa9b81f2221628ac84ab5a770649328fd7ae9963c7fcf5e5102d7"
      url "https://github.com/Loops-so/cli/releases/download/v#{version}/loops_cli_linux_arm64.tar.gz"
    end
  end

  name "loops@0.4.1"
  desc "Official CLI for Loops"
  homepage "https://loops.so"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "loops"

  # No zap stanza required

end
