# This file was generated by GoReleaser. DO NOT EDIT.
cask "loops@0.5.0" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "d907b792a981d69694ba55f3934633bdd3de25841e0bbb64027fd7f3ee91d49a"
      url "https://github.com/loops-so/cli/releases/download/v#{version}/loops_cli_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "ab2257f6025db0d803e37e8a1270bdd1a2d9adf37cd40363ff6f3f73faf0eb99"
      url "https://github.com/loops-so/cli/releases/download/v#{version}/loops_cli_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c017e003e32cee239a7f5341cb4473f16150b65f5bb8dc29bbbee371924e8762"
      url "https://github.com/loops-so/cli/releases/download/v#{version}/loops_cli_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "d03970294eeeea5b1d81a6a28786ead1cb5eee2ad4c5168d2e691273c562eb1c"
      url "https://github.com/loops-so/cli/releases/download/v#{version}/loops_cli_linux_arm64.tar.gz"
    end
  end

  name "loops@0.5.0"
  desc "Official CLI for Loops"
  homepage "https://loops.so"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "loops"

  # No zap stanza required

end
