# This file was generated by GoReleaser. DO NOT EDIT.
cask "loops@0.4.0" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "deb4ce9ebfe70933419b40d8433ae60e64c6319d978a50fd9dd0b498a28aebb9"
      url "https://github.com/Loops-so/cli/releases/download/v#{version}/loops_cli_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "4c7947aece58d0c65e0df8922edc32ccafa6a3d29cf7907c5a1fb72bb8537395"
      url "https://github.com/Loops-so/cli/releases/download/v#{version}/loops_cli_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "732ae85d6a2d614da31f7ddfe233f6918a30f9431a060c3ca7cec982d262ea15"
      url "https://github.com/Loops-so/cli/releases/download/v#{version}/loops_cli_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "ce630de5706d48551617ab37c58fde985fa670f47363e6bbc911afe828ceb279"
      url "https://github.com/Loops-so/cli/releases/download/v#{version}/loops_cli_linux_arm64.tar.gz"
    end
  end

  name "loops@0.4.0"
  desc "Official CLI for Loops"
  homepage "https://loops.so"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "loops"

  # No zap stanza required

end
