# This file was generated by GoReleaser. DO NOT EDIT.
cask "loops@0.4.2" do
  version "0.4.2"

  on_macos do
    on_intel do
      sha256 "9ee64cb6a9aaaa8bb67ca703e9746e8ca8ce9cc5eee728922aa9f842bb38a209"
      url "https://github.com/Loops-so/cli/releases/download/v#{version}/loops_cli_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "ae2c42aed293d7c9dd919a7e72cb2fd973a2f92c995147b7dfd37f9d15c20960"
      url "https://github.com/Loops-so/cli/releases/download/v#{version}/loops_cli_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "27df1abd5c49de8d5c3772ea209fc73f504de8b2fa6b8968cb2cf7ef2602367b"
      url "https://github.com/Loops-so/cli/releases/download/v#{version}/loops_cli_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "6e4221ff0e5718b2c592e6238587522cbca0c04aeeae09191505c3dad238d758"
      url "https://github.com/Loops-so/cli/releases/download/v#{version}/loops_cli_linux_arm64.tar.gz"
    end
  end

  name "loops@0.4.2"
  desc "Official CLI for Loops"
  homepage "https://loops.so"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "loops"

  # No zap stanza required

end
