# This file was generated by GoReleaser. DO NOT EDIT.
cask "loops@0.0.0" do
  version "0.0.0"

  on_macos do
    on_intel do
      url "https://github.com/Loops-so/cli/releases/download/v#{version}/loops_cli_darwin_x86_64.tar.gz"
      sha256 "1705cd1b82b1978796e6898a890b7ec13b6fda67b00ff28dd436e4f32b228d47"
    end
    on_arm do
      url "https://github.com/Loops-so/cli/releases/download/v#{version}/loops_cli_darwin_arm64.tar.gz"
      sha256 "d83376f6789d4da534ec26cc7fb2c1468cb27a187cfbbe4cfe6663d7baf090d6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Loops-so/cli/releases/download/v#{version}/loops_cli_linux_x86_64.tar.gz"
      sha256 "ebbf4bbceca3e2deea0ab16d51ae1594e6e9ebc165e63505fe05f9f226a315b5"
    end
    on_arm do
      url "https://github.com/Loops-so/cli/releases/download/v#{version}/loops_cli_linux_arm64.tar.gz"
      sha256 "111e9f5533b952814b8672122c75c694d10aa08dc03a1d6e9e4657c3f380432d"
    end
  end

  name "loops@0.0.0"
  desc "Official CLI for Loops"
  homepage "https://loops.so"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "loops"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/loops"]
    end
  end

  # No zap stanza required

end
