# This file was generated by GoReleaser. DO NOT EDIT.
cask "loops" do
  version "0.0.0-prerelease1"

  on_macos do
    on_intel do
      url "https://github.com/Loops-so/cli/releases/download/v#{version}/loops_cli_darwin_x86_64.tar.gz"
      sha256 "48c743260cf937e8fa77a85b3f362551faab94ed764301d24d547ac9f0ccdf9d"
    end
    on_arm do
      url "https://github.com/Loops-so/cli/releases/download/v#{version}/loops_cli_darwin_arm64.tar.gz"
      sha256 "44cbae83e1445c2d62d8fa9da5eb95ba2cde867904dc4d0c051c69fb2ed7ad42"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Loops-so/cli/releases/download/v#{version}/loops_cli_linux_x86_64.tar.gz"
      sha256 "697d89532e84b748ae1b0fb1d88e0b2fc24beb47da6e4825faae756c6c8ca99f"
    end
    on_arm do
      url "https://github.com/Loops-so/cli/releases/download/v#{version}/loops_cli_linux_arm64.tar.gz"
      sha256 "fdbd251ecea91b8527b4496af6d7ad96f9408a00da083fa4e0a31237a7525e29"
    end
  end

  name "loops"
  desc "Official CLI for Loops"
  homepage "https://loops.so"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "loops"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/loops"]
    end
  end

  # No zap stanza required

end
