# This file was generated by GoReleaser. DO NOT EDIT.
cask "loops" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "56505b1cf6736cd0bbee576ce5e424a100ef1b7727992f56568f73907abf5229"
      url "https://github.com/Loops-so/cli/releases/download/v#{version}/loops_cli_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "b72592cdb28a0941685b76f060d7fc9f0c7452b1a146cea84a9e76eed3af838d"
      url "https://github.com/Loops-so/cli/releases/download/v#{version}/loops_cli_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "42dd58c641e6dd37291b4d492ff7a813713d7216aa2a4fa8cd7c0beb0bb49406"
      url "https://github.com/Loops-so/cli/releases/download/v#{version}/loops_cli_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "ddb172e7de1c5f29a8dc384228bb806d26c60ece0c8b7ebe0ffc6b3ee995be68"
      url "https://github.com/Loops-so/cli/releases/download/v#{version}/loops_cli_linux_arm64.tar.gz"
    end
  end

  name "loops"
  desc "Official CLI for Loops"
  homepage "https://loops.so"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "loops"

  # No zap stanza required

end
