# This file was generated by GoReleaser. DO NOT EDIT.
cask "loops" do
  version "0.0.0"

  on_macos do
    on_intel do
      url "https://github.com/Loops-so/cli/releases/download/v#{version}/loops_cli_darwin_x86_64.tar.gz"
      sha256 "72cf4d04f4d721d59771439485435fa9de04f79c2b3961ab2dd783b9fc35fdbf"
    end
    on_arm do
      url "https://github.com/Loops-so/cli/releases/download/v#{version}/loops_cli_darwin_arm64.tar.gz"
      sha256 "0e2e2c6faf27f1a822202d3ef5a556dfee7df3bf772c42fd7ef7d6cf37b1e406"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Loops-so/cli/releases/download/v#{version}/loops_cli_linux_x86_64.tar.gz"
      sha256 "28df90be8f6e57deb8eebc8dde87f63aaeb88b31736c6bd6592720d2055f1b4f"
    end
    on_arm do
      url "https://github.com/Loops-so/cli/releases/download/v#{version}/loops_cli_linux_arm64.tar.gz"
      sha256 "625f839686b24883b8a373606d47bf95a18672bf925cc731221219423f7e834a"
    end
  end

  name "loops"
  desc "Official CLI for Loops"
  homepage "https://loops.so"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "loops"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/loops"]
    end
  end

  # No zap stanza required

end
